### PR TITLE
Update web.config and add publish tool

### PR DESCRIPTION
**Pull request by BrennanConroy**
@JunTaoLuo @Tratcher @Eilon

### CODE REVIEW

**Comment by moozzyk** [comment]
Maybe just remove web.config?

**Comment by moozzyk** [comment]
actually if you open with VS it will create a new one if one does not exist...

**Comment by moozzyk** [comment]
:ship::it:

**Comment by JunTaoLuo** [comment]
@moozzyk we decided to keep the web.config since we are emulating what is generated by templates.

**Pull request merged**
