### PR TITLE
Refactoring ProxyMiddleware

### PR DESCRIPTION
**Pull request by Marusyk**
Made refactoring for ProxyMiddleware.

Added two methods `CreateRequestMessage` and `CopyResponseAsync` to use in `Invoke`

It makes some improve of reading the code

### CODE REVIEW

**Comment by davidfowl** [comment]
What does this improve?

**Comment by Marusyk** [comment]
@davidfowl This is refactoring that improve reading of code.

**Comment by davidfowl** [comment]
> @davidfowl This is refactoring that improve reading of code.

That's questionable and I don't agree that it does.

It also introduces more async methods which isn't great for performance. It's better to have a single async methods with several awaits and the entire point of the proxy middleware is to be performant. 

Plus the method is 41 lines of code and doesn't need to be split up.

**Comment by Marusyk** [comment]
Thank you. What about `CreateRequestMessage()`? Can we leave that?

**Comment by mkosieradzki** [comment]
@Marusyk 
I am currently working on some refactoring which is designed with dynamic routing in mind ( #43 ). Since this is small module and I will change it significantly, would you mind postponing your changes until my next PR is accepted or rejected at all, because we are going to have a lot of collisions if your PR is accepted.

**Comment by davidfowl** [comment]
Sure, also rename contextRequest, to request.

**Comment by Marusyk** [comment]
Done. Thank you very much for review

**Comment by mkosieradzki** [comment]
Please do not merge this before #41 as it has multiple collisions.

**Comment by Marusyk** [comment]
No problem, I can marge it after your commit.

**Comment by Marusyk** [comment]
Merged

**Comment by Marusyk** [comment]
What is the problem with Travis build?

**Comment by Marusyk** [comment]
The build was fixed

**Comment by Marusyk** [comment]
@davidfowl Hello, could you please review my new commit?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2495

**Comment by aspnet-hello** [comment]
Sorry I was a bad bot, but unable to re-open this PR because the fork is gone.
@muratg , please let @Eilon know if this PR is still needed.

**Pull request closed without merging**
