### PR TITLE
Update README.md to indicate this project has moved to https://github.com/aspnet/AspLabs

### PR DESCRIPTION
**Pull request by natemcmaster**
Final PR before marking this repo as read-only.

### CODE REVIEW

**Comment by jkotalik** [comment]
@mikaelm12 😢

**Review by mikaelm12 — DISMISSED** [review]
No

**Comment by antmdvs** [comment]
Hi, why is it being archived? (I subscribed a long time ago and still get watch notifications but haven't been following closely.)

**Comment by natemcmaster** [comment]
We're consolidating repos. See https://github.com/aspnet/Announcements/issues/320. The code here has moved to https://github.com/aspnet/AspLabs.

**Comment by mikaelm12** [comment]
While I am actually sad to see this the change on this repo, the change looks okay I guess... 😢

**Comment by antmdvs** [comment]
Got it. Thanks

**Review by Eilon — APPROVED** [review]

**Pull request merged**
