### PR TITLE
multi domain to multi proxy host

### PR DESCRIPTION
**Pull request by chsword**
[suggest] multi domain to multi proxy host

            var dictOptions = new MultiProxyDictionaryOptions(defaultOptions = new ProxyOptions()
            {
                Scheme = scheme,
                Host = host,
                Port = port
            });
            dictOptions.Add("microsoft.proxy.com", new MultiProxyOptionsValue {Host = "www.microsoft.com"});
            dictOptions.Add("aspnet.proxy.com", new MultiProxyOptionsValue { Host = "www.asp.net" });
            dictOptions.Add("github.proxy.com", new MultiProxyOptionsValue { Host = "www.github.com" });

            app.RunProxy(dictOptions);

### CODE REVIEW

**Comment by Tratcher** [comment]
Hmm, those first two commits shouldn't be there. Did you start this work on the dev branch?

**Comment by Tratcher** [comment]
I agree we need this kind of feature (similar request here: https://github.com/aspnet/Proxy/issues/10). However the design needs a lot of work.

@muratg, this package isn't shipping with v1 correct? I think this feature should be revisited after v1.

**Comment by chsword** [comment]
sorry I start this work with master branch.

**Comment by muratg** [comment]
Agreed, this work shouldn't be from the master branch, and it requires design before actual coding. 

@Tratcher [This package](https://www.nuget.org/packages/Microsoft.AspNet.Proxy/1.0.0-rc1-final) is actually shipping (although we can revisit this for RC2 if you think that's the right approach)

**Comment by Tratcher** [comment]
Yes, I recommend this package be left as pre-release. I'm not aware of any of our primary scenarios that use it so the design hasn't had a chance to mature.

**Comment by muratg** [comment]
Cool, added this package to the "Prerelease" list.

@Tratcher Should we close this PR then?

**Pull request closed without merging**
