### PR TITLE
Create or update baselines to match 2.0

### PR DESCRIPTION
**Pull request by ryanbrandenburg**

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
Assigning @pranavkm because it's not clear who has context on this repo.

**Comment by ryanbrandenburg** [comment]
@javiercn and @Eilon looks like we might have had actual breaking changes in this repo?

**Comment by pranavkm** [comment]
AFAIK, the package in this repo is an alpha version. We shouldn't have baselines for it.

**Comment by Eilon** [comment]
@pranavkm is correct. This repo shouldn't have any baselines.

**Pull request closed without merging**
