### PR TITLE
Fixed WebSockets (subprotocol) support

### PR DESCRIPTION
**Pull request by mkosieradzki**
I think this test works again. Let's see,

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
@mikaelm12

**Comment by mkosieradzki** [comment]
I was just trying out, because this test passes on my computer on .net 461.

**Comment by JunTaoLuo** [comment]
Ah, well please only create PRs when you think it's valuable for us to consider taking the change. Would you please close this PR until you finished your experiments?

**Comment by mkosieradzki** [comment]
@mikaelm12 I did it ;)

This PR fixes:
#53 
- It also extends the list of not-forwarded Sec-WebSocket-* headers
- If fixes support for subprotocol what was the root cause for this test to fail.

Some explanation:
Earlier it was failing on Linux due to broken WebClientSocket and we disabled this test, however disabled test failed to detect a regression which was in area of subprotocol support.

**Comment by mkosieradzki** [comment]
@davidfowl would you mind merging this PR? It fixes SignalR support.

**Comment by mkosieradzki** [comment]
@mikaelm12 @davidfowl bump

**Comment by mikaelm12** [comment]
This looks good. I'm gonna let @Tratcher or @davidfowl give the final sign off though, then I'll merge this.

**Comment by mikaelm12** [comment]
Thanks for the contribution @mkosieradzki!

**Pull request merged**
